### ISSUE TITLE
[questions] Status of this project / plans

### ISSUE THREAD

**Issue by geonanorch** [ProgerXP/FileDrop#65]
Hi there

I just spent a (long) while looking at lightweight, vanilla javascript file uploaders. I like this project very much: indeed very light, **_excellent_** documentation, intuitive/natural use.

A couple of things worry me: there have been no updates since early 2015, and there is a single contributor. Now, this could mean that perfection was reached (that would be fine, no need to keep changing something that does its job well), but I would still like to ask:
- is the project still actively supported?
- are issues or pull requests welcome?

Thank you at any rate for this great contribution.

**Comment by ProgerXP** [comment]
Thanks for sharing your impression. Not a lot of people have done that despite the FileDrop's age.

> Now, this could mean that perfection was reached (that would be fine, no need to keep changing something that does its job well)

Yes, the project is pretty much finished. 

No, there are still bugs (they are open here on GitHub), mostly regarding big file uploads (more than a few megabytes). I have been planning to tackle them for quite some time but because they are not critical for my use cases I haven't done that yet. Apart from these problems, FileDrop works fine AFAIK. I don't know about any critical bugs, and FileDrop is very extensible so you can correct most problems without touching the core.

> are issues or pull requests welcome?

It depends on the pull request, generally I want to keep the code style consistent so I can do some corrections. But contributions are always welcome even if they're not accepted - they don't let me forget about the project.

**Comment by geonanorch** [comment]
Thank you for the prompt reply, I stand reassured!
I might use FileDrop for uploading photos, i.e. potentially big files. I will contact you if I find something useful...
