### ISSUE TITLE
request function, fd.serialize(form)

### ISSUE THREAD

**Issue by moscorp** [ProgerXP/FileDrop#80]
Sir, thanks for great support!
Is that possible to achieve the serialize method ?!

Thanks,

**Comment by ProgerXP** [comment]
Due to supporting old browsers FileDrop requires that only one file is sent per request (the file takes all POST data for itself). The only way to supply data is via the query string; see [this example](https://filedropjs.org/#scusdat). Therefore you should serialize data the way your application expects it, like by using jQuery's `serialize()` and appending it to `sendTo()`'s URL.
