### ISSUE TITLE
file name problem

### ISSUE THREAD

**Issue by moscorp** [ProgerXP/FileDrop#81]
Just adding some statement in upload.php and found some problem

$acceptedext = array("pdf","csv","xls","xlsx","doc","docx","jpg","tif","png","ppt","rar","zip");
$ext = strtolower(pathinfo($_FILES['fd-file']['name'], PATHINFO_EXTENSION));
if (!in_array($ext, $acceptedext)) {  
...

it works in ie(mode7) and doesn't work in ie(mode8 or above) and chrome,
it seems can't catch the file name, is there any variant am I missing ?!

**Comment by ProgerXP** [comment]
> Due to supporting old browsers FileDrop requires that only one file is sent per request (the file takes all POST data for itself). 
> https://github.com/ProgerXP/FileDrop/issues/80#issuecomment-832960937

This means `$_FILES` does not work when using drag & drop instead of <iframe> (old IE).

File name and size are given as headers instead. See the sample upload.php that I have referred you to, it will save you a lot of time. Also see the docs (`extraHeaders` [opt](https://filedropjs.org/#fm) to constructor and `sendTo()`).
